### ISSUE TITLE
Crash in upnp::log

### ISSUE THREAD

**Issue by aldenml** [arvidn/libtorrent#2220]
libtorrent version (or branch): `master`
platform/architecture: `android`
compiler and compiler version: `clang-5`

This crash happened very occasionally, but lately the frequency has incremented like 15X
```
pc 0000000000331bbc  libjlibtorrent.so (libtorrent::upnp::log(char const*, ...) const+4)
pc 000000000033291c  libjlibtorrent.so (libtorrent::upnp::update_map(libtorrent::upnp::rootdevice&, int)+172)
```

Maybe it's related to the life of the of `d` in `log("connecting to %s", d.hostname.c_str());`, but other than that, I can't see any other reason this could fail. I can't even see how `d` can become invalid, unless something in parallel touch `upnp::m_devices`. Ideas? Thanks!

**Comment by ssiloti** [comment]
The small offset in `upnp::log` means it must have died early in the function. My best theory is that the `upnp` instance somehow managed to outlive `session_impl` causing a crash in the (likely inlined) call to `upnp::should_log`, but that shouldn't be possible. Do you have a more complete stack trace?

**Comment by aldenml** [comment]
I had the same idea, but discarded it by not finding a the "how". No more info or better stack trace.

**Comment by aldenml** [comment]
something is getting out of control here, to many crash reported

**Comment by aldenml** [comment]
@ssiloti @arvidn I need some help here if/when you have time.

With the following call sequence: `session_impl::abort()->stop_upnp()->m_upnp->close()`, I see that
`upnp::close()` iterate by all mappings and try to delete them, calling `update_map`. But this last call involves potentially multiple async http connections with callbacks, in the process creating multiple `shared_ptr` of itself.

My question is: Is it possible that the session gets destructed and still there are outstanding http connections working with the upnp mappings? How the lifecycle works here?

**Comment by aldenml** [comment]
I think the answer is that everything get synchronized with `m_impl->get_io_service().dispatch([=] { ptr->abort(); });`, is that it?

**Comment by ssiloti** [comment]
The `session` and `session_impl` objects don't get destroyed until after the asio event loop and the network thread have terminated. So even if there were somehow outstanding events they would not get processed.

**Comment by ssiloti** [comment]
That is assuming you're not providing your own `io_service`. You're not are you?

**Comment by aldenml** [comment]
No, I'm using the default one

**Comment by aldenml** [comment]
Here it is another crash in `log`, but it seems related to an infinite recursion
```
backtrace:
 
  native: pc 000000000036d53c  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZNK10libtorrent4upnp3logEPKcz+4)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
 
  native: pc 000000000036e2a8  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so (_ZN10libtorrent4upnp10update_mapERNS0_10rootdeviceEi+172)
```

**Comment by aldenml** [comment]
@ssiloti I finally got the the debug symbols info

Crash report:
```
backtrace:
  native: pc 000000000027731c  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so
  native: pc 0000000000278254  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so
  native: pc 0000000000278254  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so
...
...
  native: pc 0000000000278254  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so
  native: pc 0000000000278254  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so
  native: pc 0000000000278254  /data/app/com.frostwire.android-1/lib/arm/libjlibtorrent.so
```

`master` revision: `6b55096ebd0ebf9d0587e1b645a281a1fe7331e5`
`(gdb) list *0x000000000027731c`:
```
0x27731c is in libtorrent::upnp::log(char const*, ...) const (libtorrent/src/upnp.cpp:129).
124		return m_callback.should_log_portmap(portmap_transport::upnp);
125	}
126	
127	TORRENT_FORMAT(2,3)
128	void upnp::log(char const* fmt, ...) const
129	{
130		TORRENT_ASSERT(is_single_thread());
131		if (!should_log()) return;
132		va_list v;
133		va_start(v, fmt);
```
`(gdb) list *0x0000000000278254`:
```
0x278254 is in libtorrent::upnp::update_map(libtorrent::upnp::rootdevice&, libtorrent::aux::strong_typedef<int, libtorrent::aux::port_mapping_tag, void>)
(libtorrent/src/upnp.cpp:793).
788		{
789	#ifndef TORRENT_DISABLE_LOGGING
790			log("mapping %u does not need updating, skipping", static_cast<int>(i));
791	#endif
792			m.act = portmap_action::none;
793			next(d, i);
794			return;
795		}
796	
797		TORRENT_ASSERT(!d.upnp_connection);
```

My theory is that something is creating an infinite recursion in `upnp::update_map` keeping the `upnp` object alive, but somehow `m_callback` becomes invalid? @arvidn?
